### ISSUE TITLE
Add a way to inform the user that a date has not been choosen on iOS

### ISSUE THREAD

**Issue by JohannesOehm** [NUMde/compass-numapp-frontend#20]
**Is your feature request related to a problem? Please describe.**
Currently, on iOS, a Date-Spinner is used, which is by default is set to the current date. However, this default date is not transfered into the internal application state. The only indication of this behaviour is the green color of the "Checkmark"-button on the bottom of the modal (but also the black "Checkmark"-button allows for switching the page, so he probably even won't understand its meaning) and the fact that the user cannot submit the questionnaire. 

If the user clicks back into the questionnaire, he sees that there is a value entered in the date field, but the checkmark button is not green. If the date field is combined with other (maybe optional) questions in one page, it is even harder for him to figure out why the submission fails.

If the user wants to enter today's date, he must set another date and then switch back to todays date.

**Describe the solution you'd like**
* A text field is drawn and empty by default. If the user clicks, a modal window is open to choose the date. Just like android behaviour.

**Describe alternatives you've considered**
* The default date could be automatically transferred into the questionnaireItemMap. However, this would lead to unwanted behaviour if the information of the date field is not actively filled in and left empty on purpose.
* A checkbox "I choose not to answer". Example: https://chat.fhir.org/#narrow/stream/179255-questionnaire

**Comment by JohannesOehm** [comment]
The link to the image in zulip chat doesn't work. Maybe this link does:

**Comment by GolexPrime** [comment]
I think you are right - this can be an issue in certain cases.
The same behaviour (a displayed but not set default value) can be observed when using the slider extension. In both cases the "I choose not to answer" - approach seems sufficient. I would prefer it to another modal (since there is already one open, the one displaying the date-picker/slider itself).

**Comment by mahvaezi** [comment]
I chose the first solution. The other one would work too. But I prefer not to change the answer of one question (date) from the inside of another one (checkbox). Specially because in the questionnaire JSON there is no relation between questions (as I know) like parent of ,... and so the first solution is more convenient. In Addition we get the same behavior on both IOS and Android.
I will commit my solution.

**Comment by mahvaezi** [comment]
Solved in #26.
